import sys
sys.path.append('..')
from util.base_parser import BaseParser 

class wsParamParser(BaseParser):
    def __init__(self, *arg_list, **arg_dict):
        super(wsParamParser, self).__init__(*arg_list, **arg_dict)
        self.add_argument('--l1', default=1., type=float)
        self.add_argument('--l2', default=2., type=float)
        self.add_argument('--dim_ftr', default=128, type=int)
        self.add_argument('--n_pairs', default=50, type=int)
        self.add_argument('--initmodel', default=None)
        self.add_argument('--resume', default='')
        self.add_argument('--batchSize', default=17, type=int)
        self.add_argument('--gpu', default=1, type=int)
        self.add_argument('--decay', default=0.001, type=float)
        self.add_argument('--optimizer', default='sgd', type=str)
        self.add_argument('--margin', default=1, type=float)
        self.add_argument('--test', action='store_true', default=False)
        self.add_argument('--dbSet', default='otb', type=str)
        self.add_argument('--num_workers', default=0, type=int)
        self.add_argument('--k_img', default=1, type=int)
        self.add_argument('--k_prp', default=20, type=int)
        self.add_argument('--maxWL', default=15, type=int)
        self.add_argument('--visIter', default=5, type=int)
        self.add_argument('--evalIter', default=10, type=int)
        self.add_argument('--epSize', default=10000, type=int)
        self.add_argument('--logFd', default='../data/log/wsEmb', type=str)
        self.add_argument('--saveEp', default=10, type=int)
        self.add_argument('--outPre', default='../data/models/a2d_checkpoint_', type=str)
        self.add_argument('--biLoss', action='store_true', default=False)
        self.add_argument('--lossW', action='store_true', default=False)
        self.add_argument('--lamda', default=0.8, type=float)
        self.add_argument('--vwFlag', action='store_true', default=False)
        self.add_argument('--wsMode', default='rank', type=str)
        self.add_argument('--hdSize', default=128, type=int)
        self.add_argument('--vocaSize', default=1312, type=int)
        self.add_argument('--conSecFlag', action='store_true', default=False)
        self.add_argument('--conFrmNum', default=9, type=int)
        self.add_argument('--moduleNum', default=2, type=int)
        self.add_argument('--moduleHdSize', default=1024, type=int)
        self.add_argument('--stEp', default=0, type=int)
        self.add_argument('--keepKeyFrameOnly', action='store_true', default=False)
        self.add_argument('--visRsFd', default='../data/visResult/rank_', type=str)
        self.add_argument('--logFdTx', default='../data/log/wsEmb', type=str)
        self.add_argument('--set_name', default='train_val', type=str)
        self.add_argument('--isParal', action='store_true', default=False)

def parse_args():
    parser = wsParamParser()
    args = parser.parse_args()
    return args
